/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
Author: YANGGA (https://sketchfab.com/YANGGA)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-room-2561ec6948a44edd87650f3a454e3722
Title: Japanese Room
*/

import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/models/optimized-room.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.blue_green} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.blue_green} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.katana_1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.katana_2} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.milk} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.texture} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.GREY} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.brown} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.dark_blue} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.dark_brown} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.green} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.light_green} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['table.001']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.teh_pot} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.wall} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.white} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.yellow} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/optimized-room.glb')
