/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 telephone.glb 
Author: 3D Share (https://sketchfab.com/3dsharesg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/telephone-7aeae41398f34c4fa5de50c2e6276b11
Title: Telephone
*/

import { useGLTF } from '@react-three/drei'

export function Telephone(props) {
  const { nodes, materials } = useGLTF('/models/telephone.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -0.079]}>
        <mesh geometry={nodes['Telephone_Material_#57_0'].geometry} material={materials.Material_57} position={[0.662, 1.903, -0.996]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/telephone.glb')
